development:
  adapter: async
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: hmc-rails5_production
